[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "requests>=2.32.4",
    "websocket>=0.2.1",
    "websockets>=15.0.1",
    "websockify>=0.13.0",
]
